package archive.adapters.postgres

class PostgresSchemaInitializer(
    private val connectionFactory: JdbcConnectionFactory,
) {
    fun initialize() {
        connectionFactory.open().use { connection ->
            connection.createStatement().use { statement ->
                statement.execute(
                    """
                    create table if not exists archive_events (
                        id bigint generated by default as identity primary key,
                        event_type varchar(255) not null,
                        aggregate_id varchar(255) not null,
                        payload_json text not null,
                        occurred_at timestamp with time zone not null default current_timestamp
                    )
                    """.trimIndent()
                )
                statement.execute(
                    """
                    create table if not exists archive_event_tags (
                        event_id bigint not null,
                        tag varchar(255) not null,
                        primary key (event_id, tag),
                        foreign key (event_id) references archive_events(id) on delete cascade
                    )
                    """.trimIndent()
                )
                statement.execute(
                    """
                    create table if not exists document_ingest_views (
                        document_id varchar(255) primary key,
                        status varchar(64) not null,
                        checksum_algorithm varchar(64) not null,
                        checksum_value varchar(255) not null,
                        file_name varchar(1024) not null,
                        content_type varchar(255) not null,
                        document_type_hint varchar(255),
                        source_system varchar(255) not null,
                        business_key varchar(255) not null,
                        last_updated_at timestamp with time zone not null default current_timestamp
                    )
                    """.trimIndent()
                )
                statement.execute(
                    "alter table document_ingest_views add column if not exists last_updated_at timestamp with time zone not null default current_timestamp"
                )
                statement.execute(
                    """
                    create index if not exists idx_archive_events_aggregate_id
                    on archive_events (aggregate_id)
                    """.trimIndent()
                )
                statement.execute(
                    """
                    create index if not exists idx_archive_event_tags_tag
                    on archive_event_tags (tag)
                    """.trimIndent()
                )
            }
        }
    }
}
